name: Auto Golang Lint And Unitest

on:
  pull_request: {}
  push:
    branches:
      - main
      - release-*
  workflow_dispatch:
    inputs:
      ref:
        description: "branch, sha, tag"
        required: true
        default: main
  workflow_call:
    inputs:
      ref:
        required: true
        type: string

permissions: write-all

# concurrency:
#   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
#   cancel-in-progress: true

jobs:
  unitest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          ref: ${{ needs.filter_changes.outputs.ref }}

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.0'

      - name: Checkout ENV go version
        run: go version

      # unitest and e2e, _test.go
      - name: Check label of All test go
        run: |
          make check_test_label

      # ================= unitest
      - name: Run unitest
        id: unitest
        continue-on-error: true
        run: |
          sudo make unitest-tests

      - name: Upload Coverage Artifact
        if: ${{ steps.unitest.outcome == 'failure' }}
        uses: actions/upload-artifact@v3.1.0
        with:
          name: coverage.out
          path: coverage.out
          retention-days: 1

      - name: Upload Report Artifact
        if: ${{ steps.unitest.outcome == 'failure' }}
        uses: actions/upload-artifact@v3.1.0
        with:
          name: unitestreport.json
          path: unitestreport.json
          retention-days: 1

      - name: Result
        if: ${{ steps.unitest.outcome == 'failure' }}
        run: |
          echo "unitest failed"
          exit 1
